### PR TITLE
[2.0] Allow logging webhook triggers

### PR DESCRIPTION
**Pull request by phroggyy**
This is a fairly large PR, and it does a few things aside from what the title says:

- [x] Allow users to enable logging of webhooks (defaults to active with a 50 logs/hook limit)
- [x] Make code more testable by clearer separation
- [x] Separate the execution of the event handler out into a separate job
- [x] New migration system to allow creating multiple migrations, this will make upgrading easier as it just requires publishing the latest files

**Upgrade notes**

This introduces a logger as part of the Job. This means that users need to run the latest migration, by first publishing the latest migration files and calling `php artisan migrate`.

- No need for a custom service provider, you now declare your listeners in the config file!
- Request data is now *not* automatically JSON encoded, this is instead done by the `transformer` in config. By default, the function is a simple JSON encode.

**Final comments**

The package is still lacking some structure. However, I did not want to restructure the entire application in this pull request. In the future, a goal should be to get rid of getters and setters only used for testing purposes, and instead resolved out of the IoC container, for a start. Abstracting out Guzzle might also be useful for testing purposes, and same goes for the logging module.

### CODE REVIEW

**Comment by mpociot** [comment]
First of all - thank you for this PR. 

There are a few things that I'd like to be changed prior to merging it and tagging it 2.0.

- The log model is called `CaptainHookLog` while the hook model is called `Webhook` (same for the tables). 
Please adjust the log model (and table) name to `WebhookLog` so it remains consistent with the existing model.

- Please add a `hasMany` relation between the Webhook and the WebhookLog models.

I think it might be better to have control of how many logs should be stored per webhook and not overall. Especially in a multi-tenant setup I want to be able to see the latest logs and don't have them cleaned up because some other tenant fired a hook. 

So instead of configuring the `storage_time` I think it's better to configure the max amount of logs _per webhook_. This way it would be possible to always have at least one log of the last called hook.

What do you think of this?

**Comment by phroggyy** [comment]
Right, so you'd make the times an array with the webhook FQCN as key and
amount as value?
ti 26. tammikuuta 2016 klo 20.13 Marcel Pociot <notifications@github.com>
kirjoitti:

**Comment by mpociot** [comment]
No I wouldn't make it that complicated. Just a single value to define how many logs per webhook will be stored.

**Comment by phroggyy** [comment]
Ah, sorry, misunderstood ya, so a single number per webhook :) I'll get that done

**Comment by mpociot** [comment]
:tada: thanks for this PR!

**Pull request merged**
