### PR TITLE
Feature/fixes by pionect

### PR DESCRIPTION
**Pull request by dducro**
Hey,

I changed the following things:

- Check if migrations ran in service provider before querying the database. 
      If the package is added by a deploy service, it fails because it tries to fetch webhooks before the migrations are run.
- Remove dynamic migration dates.
      This is because I needed to change the migration in an other package in stead of the underlying Laravel project. It's impossible to override a migration in an other package if "vendor:publish" is run by a deploy service and the migration name is unknown. (the files are copied after all the service providers have been triggered, so the check if the migration already exists doesn't work in this case)
- made tenant_id unsigned
      This is done so I can set a foreign key to another table.
- add missing : to eloquent events in README
      The webhooks weren't triggering because I missed a : in the event name.

Hope I provided enough info and you accept this pull request! :)

### CODE REVIEW

**Comment by mpociot** [comment]
Thanks for the PR!

Do you have any idea on why the tests are failing on 5.6 and 7.0?

**Comment by dducro** [comment]
Hey,

Thanks for your response!
I haven't checked the tests, but I noticed the the current build status on master is failing.
So I assumed it had something to do with the tests or a earlier PRs.

Let me know if I can do anything.

**Comment by dducro** [comment]
The migrations don't work in CommandsTest, so the tests that use the database fail..

**Comment by dducro** [comment]
Tests green :)

**Comment by mpociot** [comment]
That's awesome! Also thanks for modifying the strings to `::class` ❤️

**Pull request merged**
